apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app-demo
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins-app-demo
  template:
    metadata:
      labels:
        app: jenkins-app-demo
    spec:
      containers:
      - image: yexia/jenkins-demo:test
        imagePullPolicy: IfNotPresent
        name: jenkins-app-demo
